# Based on https://github.com/sainnhe/gruvbox-material by sainnhe
# Gruvbox Material — dark, medium, material foreground
cursor                  #928374
cursor_text_color       background
url_color               #7daea3
visual_bell_color       #89b482
bell_border_color       #89b482
active_border_color     #d3869b
inactive_border_color   #5a524c
foreground              #d4be98
background              #282828
selection_foreground    #928374
selection_background    #d4be98
active_tab_foreground   #d4be98
active_tab_background   #5a524c
inactive_tab_foreground #a89984
inactive_tab_background #3c3836

# black (bg3/bg4)
color0                  #5A524C
color8                  #5A524C

# red
color1                  #ea6962
color9                  #ea6962

# green
color2                  #a9b665
color10                 #a9b665

# yellow
color3                  #d8a657
color11                 #d8a657

# blue
color4                  #7daea3
color12                 #7daea3

# purple
color5                  #d3869b
color13                 #d3869b

# aqua
color6                  #89b482
color14                 #89b482

# white (fg)
color7                  #D4BE98
color15                 #D4BE98

font_family        FiraCode
bold_font          auto
italic_font        auto
bold_italic_font   auto

disable_ligatures always
window_padding_width 8
