general {
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    path = ~/wallpapers/stray_cafe.jpg
    blur_passes = 1
    blur_size = 1
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.3
    dots_center = false
    outer_color = rgb(45403d)
    inner_color = rgb(282828)
    font_color = rgb(d4be98)
    placeholder_text = <i>Password...</i>
    fail_color = rgb(ea6962)
    fail_text = <i>$FAIL</i>
    halign = center
    valign = center   
    position = 0, -20
}

label {
    monitor =
    text = $TIME
    color = rgb(d4be98)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}
