[mgr]
show_hidden = true

[opener]
neovim = [
  { run = 'nvim "$@"', block = true, desc = "Neovim" },
]
vscode = [
  { run = 'code "$@"', orphan = true, desc = "VSCode" },
]
reveal = [
  { run = 'thunar "$(dirname "$@")"', orphan = true, desc = "Reveal in Thunar" },
]
vlc = [
  { run = 'vlc "$@"', orphan = true, desc = "VLC" },
]
run_script = [
  { run = "$@", block = true, desc = "Run script" }
]
execute = [
  { run = "$@", orphan = true, desc = "Execute" }
]
umu = [
  { run = "kitty umu-run $@", orphan = true, desc = "umu-run" }
]
extract_with_ouch = [
  { run = 'ouch decompress "$@"', block = false, desc = "Extract here (ouch)" }
]

[open]
prepend_rules = [
  { url = "*.sh", use = [ "neovim", "vscode", "run_script"] },
  { url = "*.exe", use = [ "umu" ] },
  { mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}", use = [ "extract_with_ouch", "reveal" ] },
  { mime = "application/{executable,pie-executable}", use = [ "execute", "reveal" ]},
  { mime = "text/*", use = [ "neovim", "vscode" ] },
  { mime = "video/*", use = "vlc" },
  { mime = "audio/*", use = "vlc" },
]

[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"

[[plugin.prepend_previewers]]
mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}"
run  = "ouch"
